services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_app
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  db:
    image: postgres:14
    container_name: demo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0-alpine
    container_name: demo_redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
